/**:
  ros__parameters:
    port: "/dev/tty_arduino"
    baud_rate: 115200
    max_speed: 2000.0
    acceleration: 2000.0
    steps: 800
    direction: 1
    continuous: true
    imu_frame_id: "imu_link" 