/**:
  ros__parameters:
    port: "/dev/tty_arduino"
    baud_rate: 115200
    max_speed: 4000       # Set to the known good speed
    acceleration: 4000  # Set to the known good acceleration
    steps: 800              # Number of steps for non-continuous mode
    direction: 1
    continuous: true
    imu_frame_id: "imu_link" 